### ISSUE TITLE
consider supporting H265/HEVC streaming over RTMP? 

### ISSUE THREAD

**Issue by c1ngular** [zboya/sms#1]
It would be great if h265 streaming over RTMP could be supported ,  please check this link: https://github.com/ksvc/FFmpeg/wiki , this project has extended FFmpeg to support with feature already , it seems a very practical solution so far , would you please consider to support this feature ?

or could you give me some guidances how to implement this feature , i am a total newbie to media and streaming technology, haven't got any clue how and where to get started .  

thank you

**Comment by zboya** [comment]
Thank you for your attention, but the project is no longer maintained.

**Comment by zboya** [comment]
If you want to  implement h265 feature, you can look dir https://github.com/sheepbao/sms/tree/master/src/vendor/sheepbao.com/media/parser  and code

**Comment by believerchen** [comment]
src/main/main.go:17:2: cannot find package "sheepbao.com/glog" in any of:
	/usr/lib/go/src/pkg/sheepbao.com/glog (from $GOROOT)
	/home/chen/go/src/sms/src/sheepbao.com/glog (from $GOPATH)
src/main/main.go:18:2: cannot find package "sheepbao.com/media/av" in any of:
	/usr/lib/go/src/pkg/sheepbao.com/media/av (from $GOROOT)
	/home/chen/go/src/sms/src/sheepbao.com/media/av (from $GOPATH)
src/main/main.go:19:2: cannot find package "sheepbao.com/media/container/flv" in any of:
	/usr/lib/go/src/pkg/sheepbao.com/media/container/flv (from $GOROOT)
	/home/chen/go/src/sms/src/sheepbao.com/media/container/flv (from $GOPATH)
src/main/main.go:20:2: cannot find package "sheepbao.com/media/protocol/hls" in any of:
	/usr/lib/go/src/pkg/sheepbao.com/media/protocol/hls (from $GOROOT)
	/home/chen/go/src/sms/src/sheepbao.com/media/protocol/hls (from $GOPATH)
src/main/main.go:21:2: cannot find package "sheepbao.com/media/protocol/httpflv" in any of:
	/usr/lib/go/src/pkg/sheepbao.com/media/protocol/httpflv (from $GOROOT)
	/home/chen/go/src/sms/src/sheepbao.com/media/protocol/httpflv (from $GOPATH)
src/main/main.go:22:2: cannot find package "sheepbao.com/media/protocol/httpopera" in any of:
	/usr/lib/go/src/pkg/sheepbao.com/media/protocol/httpopera (from $GOROOT)
	/home/chen/go/src/sms/src/sheepbao.com/media/protocol/httpopera (from $GOPATH)
src/main/main.go:23:2: cannot find package "sheepbao.com/media/protocol/rtmp" in any of:
	/usr/lib/go/src/pkg/sheepbao.com/media/protocol/rtmp (from $GOROOT)
	/home/chen/go/src/sms/src/sheepbao.com/media/protocol/rtmp (from $GOPATH

**Comment by believerchen** [comment]
编译出错了 在ubuntu 上 
src/main/main.go:17:2: cannot find package "sheepbao.com/glog" in any of:
/usr/lib/go/src/pkg/sheepbao.com/glog (from $GOROOT)
/home/chen/go/src/sms/src/sheepbao.com/glog (from $GOPATH)
src/main/main.go:18:2: cannot find package "sheepbao.com/media/av" in any of:
/usr/lib/go/src/pkg/sheepbao.com/media/av (from $GOROOT)
/home/chen/go/src/sms/src/sheepbao.com/media/av (from $GOPATH)
src/main/main.go:19:2: cannot find package "sheepbao.com/media/container/flv" in any of:
/usr/lib/go/src/pkg/sheepbao.com/media/container/flv (from $GOROOT)
/home/chen/go/src/sms/src/sheepbao.com/media/container/flv (from $GOPATH)
src/main/main.go:20:2: cannot find package "sheepbao.com/media/protocol/hls" in any of:
/usr/lib/go/src/pkg/sheepbao.com/media/protocol/hls (from $GOROOT)
/home/chen/go/src/sms/src/sheepbao.com/media/protocol/hls (from $GOPATH)
src/main/main.go:21:2: cannot find package "sheepbao.com/media/protocol/httpflv" in any of:
/usr/lib/go/src/pkg/sheepbao.com/media/protocol/httpflv (from $GOROOT)
/home/chen/go/src/sms/src/sheepbao.com/media/protocol/httpflv (from $GOPATH)
src/main/main.go:22:2: cannot find package "sheepbao.com/media/protocol/httpopera" in any of:
/usr/lib/go/src/pkg/sheepbao.com/media/protocol/httpopera (from $GOROOT)
/home/chen/go/src/sms/src/sheepbao.com/media/protocol/httpopera (from $GOPATH)
src/main/main.go:23:2: cannot find package "sheepbao.com/media/protocol/rtmp" in any of:
/usr/lib/go/src/pkg/sheepbao.com/media/protocol/rtmp (from $GOROOT)
/home/chen/go/src/sms/src/sheepbao.com/media/protocol/rtmp (from $GOPATH

**Comment by zboya** [comment]
@believerchen 请告知你怎么编译的？ 执行`./bulid.sh`吗？还是go build， Readme里有说怎么编译，请参考。

**Comment by zboya** [comment]
@believerchen  并且你这是另一个问题，不应该在这个issue上提问，应该新开一个issue

**Comment by believerchen** [comment]
@sheepbao 跟readme 一样的操作 显示找不到文件
git clone https://github.com/sheepbao/sms.git  
cd sms  
./build.sh

**Comment by zboya** [comment]
@believerchen 我自己测试没问题，找不到文件无非两个原因，第一，文件真的不存在，第二gopath设置不对，你自己排查一下。
